spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

      security:
        oauth2:
          client:
            registration:
              google:
                client-id: 52700434993-tdmbl9e2rvrrkm11n1rc39oqba8vnsl7.apps.googleusercontent.com
                client-secret: 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
                scope:
                  - email
                  - profile

jwt:
  issuer: zesthj@gmail.com
  secret_key: springboot-jwt